name: Ranks
author: ItzBulkDev
main: TitaniumDonate\Main
version: 1.0
api: [1.12.0]
commands:
  ranks:
    description: List of ranks
    permission: ranks.command
permissions:
  ranks.command:
    default: true
    description: "List of ranks"

